### ISSUE TITLE
Algorithm needs to be determined for the bias of whole article

### ISSUE THREAD

**Issue by LostLaser** [LostLaser/Daratos#19]
We are running the neural network on a sentence by sentence basis but we need to find a way to determine if a whole article is biased based on each individual sentence.

**Comment by fernandotoress** [comment]
Hey there, would you be interested in integrating your chrome extension with The Bipartisan Press's AI? It's pretty capable of predict whole article bias. If you are, please send us an email. Thanks!

**Comment by LostLaser** [comment]
@fernandotoress Great to hear from you! I would at the very least be interested in learning more about it. Is this the correct email? support@thebipartisanpress.com

**Comment by fernandotoress** [comment]
Yep. That will do

**Comment by LostLaser** [comment]
Closing this one out. Bias dependency has been switched to the bipartisan press' AI.
